### ISSUE TITLE
Repeat efforts/similar project

### ISSUE THREAD

**Issue by TheJaredWilcurt** [nwutils/electron-to-nwjs#2]
Hey there, I started a project to map out the Electron API and produce NW.js viable alternatives to all the options:

* https://github.com/nwutils/nw-electron-adapter

Unfortunately there was very little interest in this by community members at the time, so I have not given it any more focus. I still think it's a good idea. And you seem to have that interest.

If more of the Electron API could be mapped to NW.js or native Node, then the adapter could act as a drop-in-replacement for many electron apps. That library could be used as a dependency in this repo as well.

But as it stands, it is mostly just documenting what needs to be done, and lacking in implementation.

Other community projects can be seen here:

* https://nwutils.io

If you'd like to move your repo into the nwutils organization, I'll add you as a member so you can keep complete control over your repo and it's direction. The main benefit of it living there is that it brings more attention to it, and there are more community members who may be able to help maintain the project in the future.

* https://github.com/nwutils

I'm available on Gitter chat if you have questions/feedback:

* https://gitter.im/nwjs/nw.js

**Comment by vitor251093** [comment]
Migration complete
